spring:
  application:
    name: uaa
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql:3306/uaa_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${MYSQL_ROOT_PASSWORD:YOUR_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0

  security:
    oauth2:
      authorization-server:
        enabled: true
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:YOUR_GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET:YOUR_GITHUB_CLIENT_SECRET}
            scope: read:user,user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

  ldap:
    urls: ldap://openldap:389
    base: dc=luban-cae,dc=com
    manager-dn: cn=admin,dc=luban-cae,dc=com
    manager-password: ${LDAP_ADMIN_PASSWORD:YOUR_LDAP_PASSWORD}

server:
  port: 9000
  error:
    include-message: always
    include-binding-errors: always

app:
  issuer: http://microservice-uaa:9000

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.ldap: DEBUG
    org.springframework.security.ldap: DEBUG
