server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud/spring-cloud-config
          default-label: main
          search-paths: src/main/resources/config
          skip-ssl-validation: true

eureka:
  instance:
    hostname: discovery
    port: 8761
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
